/* Campbell datalogger files */

-- I might do this later but not for now
/*
create table campbell_common (
  file text not null,
  timestamp timestamp not null,
  record int,
  no_avg numeric,
  no2_avg numeric,
  ozone_avg numeric,
  co_avg numeric,
  so2_avg numeric,
  t_avg numeric,
  rh_avg numeric,
  bp_avg numeric,
  ptemp_c_avg numeric,
  batt_volt_avg numeric,
  f_co_avg numeric,
  f_nox_avg numeric
);
*/

create table campbell_wfms (
  file text not null,
  instrument_time timestamp primary key,
  record int,
  no_avg numeric,
  no2_avg numeric,
  noy_avg numeric,
  ozone_avg numeric,
  co_avg numeric,
  so2_avg numeric,
  lamp_avg numeric,
  t_avg numeric,
  rh_avg numeric,
  ws3cup_avg numeric,
  ws_ms_avg numeric,
  winddir_avg numeric,
  ws_ms_s_wvt numeric,
  winddir_d1_wvt numeric,
  winddir_sd1_wvt numeric,
  ws3cup_max numeric,
  ws3cupb_avg numeric,
  ws3cupb_s_wvt numeric,
  ws3cupb_max numeric,
  bp_avg numeric,
  slrw_avg numeric,
  ws_ms_max numeric,
  rain_mm_tot numeric,
  ptemp_c_avg numeric,
  batt_volt_avg numeric,
  f_co_avg numeric,
  f_noy_avg numeric,
  f_so2_avg numeric,
  f_nox_avg numeric,
  f_trh_avg numeric,
  f_wind_avg numeric
);
SELECT create_hypertable('campbell_wfms', 'instrument_time');

create table campbell_wfml (
  file text not null,
  instrument_time timestamp primary key,
  record int,
  no_avg numeric,
  no2_avg numeric,
  nox_avg numeric,
  bp2_avg numeric,
  ozone_avg numeric,
  co_avg numeric,
  so2_avg numeric,
  methane_avg numeric,
  nmhc_avg numeric,
  t_avg numeric,
  rh_avg numeric,
  ws_avg numeric,
  wd_avg numeric,
  mean_wind_speed numeric,
  vector_mean_dir numeric,
  sd_wind_dir numeric,
  bp_avg numeric,
  pm25_avg numeric,
  ngn3_avg numeric,
  ptemp_c_avg numeric,
  batt_volt_avg numeric,
  f_nox_avg numeric,
  f_co_avg numeric,
  f_ngn_avg numeric
);
SELECT create_hypertable('campbell_wfml', 'instrument_time');


/* Process the WFMS campbell data */
CREATE materialized VIEW processed_campbell_wfms AS
  select time,
	 no,
	 -- ugh need to add source to campbell tables for manual flag
	 -- matching
	 is_flagged('NO', 1, null, time,
		    no, f_nox_avg::text, median_no::numeric,
		    mad_no::numeric) as no_flagged,
	 no2,
	 is_flagged('NO2', 1, null, time,
		    no2, f_nox_avg::text, median_no2::numeric,
		    mad_no2::numeric) as no2_flagged,
	 noy,
	 is_flagged('NOy', 1, null, time,
		    noy, f_noy_avg::text, median_noy::numeric,
		    mad_noy::numeric) as noy_flagged,
	 ozone,
	 is_flagged('Ozone', 1, null, time,
		    ozone, null, median_ozone::numeric,
		    mad_ozone::numeric) as ozone_flagged,
	 co,
	 is_flagged('CO', 1, null, time,
		    co, f_co_avg::text, median_co::numeric,
		    mad_co::numeric) as co_flagged,
	 so2,
	 is_flagged('SO2', 1, null, time,
		    so2, f_so2_avg::text, median_so2::numeric,
		    mad_so2::numeric) as so2_flagged,
	 temp,
	 is_flagged('T', 1, null, time,
		    temp, f_trh_avg::text, median_temp::numeric,
		    mad_temp::numeric) as temp_flagged,
	 rh,
	 is_flagged('RH', 1, null, time,
		    rh, f_trh_avg::text, median_rh::numeric,
		    mad_rh::numeric) as rh_flagged,
	 ws,
	 is_flagged('WS', 1, null, time,
		    ws, f_wind_avg::text, null,
		    null) as ws_flagged,
	 wd,
	 is_flagged('WD', 1, null, time,
		    wd, f_wind_avg::text, null,
		    null) as wd_flagged,
	 wd_v,
	 is_flagged('WD_V', 1, null, time,
		    wd_v, null, null,
		    null) as wd_v_flagged,
	 ws_max,
	 is_flagged('WS_MAX', 1, null, time,
		    ws_max, f_wind_avg::text, null,
		    null) as ws_max_flagged,
	 bp,
	 is_flagged('BP', 1, null, time,
		    bp, null, median_bp::numeric,
		    mad_bp::numeric) as bp_flagged
    from (select instrument_time as time,
	         -- collect rolling medians and MADs for flagging
		 no,
		 median(no) over w as median_no,
		 mad(no) over w as mad_no,
		 no2,
		 median(no2) over w as median_no2,
		 mad(no2) over w as mad_no2,
		 f_nox_avg,
		 noy,
		 median(noy) over w as median_noy,
		 mad(noy) over w as mad_noy,
		 f_noy_avg,
		 ozone,
		 median(ozone) over w as median_ozone,
		 mad(ozone) over w as mad_ozone,
		 co,
		 median(co) over w as median_co,
		 mad(co) over w as mad_co,
		 f_co_avg,
		 so2,
		 median(so2) over w as median_so2,
		 mad(so2) over w as mad_so2,
		 f_so2_avg,
		 temp,
		 median(temp) over w as median_temp,
		 mad(temp) over w as mad_temp,
		 rh,
		 median(rh) over w as median_rh,
		 mad(rh) over w as mad_rh,
		 f_trh_avg,
		 ws,
		 wd,
		 wd_v,
		 ws_max,
		 f_wind_avg,
		 bp,
		 median(bp) over w as median_bp,
		 mad(bp) over w as mad_bp
	    from (select *,
		         -- calibrate everything
			 apply_calib(1, 'NO', no_avg, instrument_time) as no,
			 -- these two need to be calibrated when
			 -- manual calibrations are added
			 no2_avg as no2,
			 noy_avg as noy,
			 ozone_avg as ozone,
			 apply_calib(1, 'CO', co_avg, instrument_time) as co,
			 apply_calib(1, 'SO2', so2_avg, instrument_time) as so2,
			 t_avg as temp,
			 rh_avg as rh,
			 -- get the max recorded wind speed
			 ws3cup_avg as ws,
			 winddir_avg % 360 as wd,
			 winddir_d1_wvt % 360 as wd_v,
			 ws3cup_max as ws_max,
			 bp_avg as bp
		    from campbell_wfms
		   limit 1000) c1
	  WINDOW w AS (ORDER BY instrument_time
		       rows between 20 preceding and 20 following)) c2;
