/* Organizing various data contained in envidas files */

create table envidas_wfms (
  station_id int references stations,
  file text,
  row int,
  instrument_time timestamp,
  record int,
  temperature numeric,
  rh numeric,
  temp_rh_flag numeric,
  ptemp numeric,
  bp numeric,
  rain numeric,
  ws3cup numeric,
  ws3cup_max numeric,
  winddir numeric,
  winddir_d1_wvt numeric,
  winddir_sd1_wvt numeric,
  ws_ms numeric,
  ws_ms_s_wvt numeric,
  ws_ms_max numeric,
  ws3cupb numeric,
  ws3cupb_s_wvt numeric,
  ws3cupb_max numeric,
  wind_flag numeric,
  no numeric,
  no2 numeric,
  nox_flag numeric,
  noy numeric,
  noy_flag numeric,
  ozone numeric,
  co numeric,
  co_flag numeric,
  so2 numeric,
  so2_flag numeric,
  batt_volt numeric,
  lamp numeric,
  slrw numeric,
  slrmj numeric,
  primary key(station_id, file, row)
);
